# Continuous Control

---

In this notebook, you will learn how to use the Unity ML-Agents environment for the second project of the [Deep Reinforcement Learning Nanodegree](https://www.udacity.com/course/deep-reinforcement-learning-nanodegree--nd893) program.

### 1. Start the Environment

We begin by importing the necessary packages.  If the code cell below returns an error, please revisit the project instructions to double-check that you have installed [Unity ML-Agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md) and [NumPy](http://www.numpy.org/).

In [1]:
from unityagents import UnityEnvironment
import numpy as np

Next, we will start the environment!  **_Before running the code cell below_**, change the `file_name` parameter to match the location of the Unity environment that you downloaded.

- **Mac**: `"path/to/Reacher.app"`
- **Windows** (x86): `"path/to/Reacher_Windows_x86/Reacher.exe"`
- **Windows** (x86_64): `"path/to/Reacher_Windows_x86_64/Reacher.exe"`
- **Linux** (x86): `"path/to/Reacher_Linux/Reacher.x86"`
- **Linux** (x86_64): `"path/to/Reacher_Linux/Reacher.x86_64"`
- **Linux** (x86, headless): `"path/to/Reacher_Linux_NoVis/Reacher.x86"`
- **Linux** (x86_64, headless): `"path/to/Reacher_Linux_NoVis/Reacher.x86_64"`

For instance, if you are using a Mac, then you downloaded `Reacher.app`.  If this file is in the same folder as the notebook, then the line below should appear as follows:
```
env = UnityEnvironment(file_name="Reacher.app")
```

In [2]:
!ls Reacher_Linux/Reacher.x86_64

ls: cannot access 'Reacher_Linux/Reacher.x86_64': No such file or directory


In [3]:
env = UnityEnvironment(file_name='../Reacher_Linux20/Reacher.x86_64', no_graphics=True)

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		goal_speed -> 1.0
		goal_size -> 5.0
Unity brain name: ReacherBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 33
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): 4
        Vector Action descriptions: , , , 


In [4]:
env.brain_names

['ReacherBrain']

Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

In [5]:
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

### 2. Examine the State and Action Spaces

In this environment, a double-jointed arm can move to target locations. A reward of `+0.1` is provided for each step that the agent's hand is in the goal location. Thus, the goal of your agent is to maintain its position at the target location for as many time steps as possible.

The observation space consists of `33` variables corresponding to position, rotation, velocity, and angular velocities of the arm.  Each action is a vector with four numbers, corresponding to torque applicable to two joints.  Every entry in the action vector must be a number between `-1` and `1`.

Run the code cell below to print some information about the environment.

In [6]:
# reset the environment
env_info = env.reset(train_mode=True)[brain_name]

# number of agents
num_agents = len(env_info.agents)
print('Number of agents:', num_agents)

# size of each action
action_size = brain.vector_action_space_size
print('Size of each action:', action_size)

# examine the state space 
states = env_info.vector_observations
state_size = states.shape[1]
print('There are {} agents. Each observes a state with length: {}'.format(states.shape[0], state_size))
print('The state for the first agent looks like:', states[0])

Number of agents: 20
Size of each action: 4
There are 20 agents. Each observes a state with length: 33
The state for the first agent looks like: [ 0.00000000e+00 -4.00000000e+00  0.00000000e+00  1.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -1.00000000e+01  0.00000000e+00
  1.00000000e+00 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  5.75471878e+00 -1.00000000e+00
  5.55726624e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
 -1.68164849e-01]


### 3. Take Random Actions in the Environment

In the next code cell, you will learn how to use the Python API to control the agent and receive feedback from the environment.

Once this cell is executed, you will watch the agent's performance, if it selects an action at random with each time step.  A window should pop up that allows you to observe the agent, as it moves through the environment.  

Of course, as part of the project, you'll have to change the code so that the agent is able to use its experience to gradually choose better actions when interacting with the environment!

In [7]:
num_agents

20

In [8]:
env_info = env.reset(train_mode=False)[brain_name]     # reset the environment    
states = env_info.vector_observations                  # get the current state (for each agent)
scores = np.zeros(num_agents)                          # initialize the score (for each agent)
while True:
    actions = np.random.randn(num_agents, action_size) # select an action (for each agent)
    actions = np.clip(actions, -1, 1)                  # all actions between -1 and 1
    print("actions", actions)
    env_info = env.step(actions)[brain_name]           # send all actions to tne environment
    next_states = env_info.vector_observations         # get next state (for each agent)
    print("satate", next_states)
    rewards = env_info.rewards                         # get reward (for each agent)
    print("reward", rewards)
    dones = env_info.local_done                        # see if episode finished
    print(dones)
    scores += env_info.rewards                         # update the score (for each agent)
    states = next_states                               # roll over states to next time step
    break
    if np.any(dones):                                  # exit loop if episode finished
        break
print('Total score (averaged over agents) this episode: {}'.format(np.mean(scores)))

actions [[-1.          1.         -0.2833117  -1.        ]
 [-0.68784199  0.67619439 -0.4187294  -0.2332782 ]
 [-1.          1.          0.13977626 -1.        ]
 [-1.          1.          0.0584136  -1.        ]
 [-0.11894936 -0.54261679 -0.13665101  0.60947615]
 [ 0.0414836   1.          1.         -1.        ]
 [ 0.47709148  0.40958684 -0.31689156  1.        ]
 [ 0.91057798 -0.47816903 -0.13757144 -1.        ]
 [ 1.         -0.02331755  1.         -0.46974311]
 [-0.41451796  0.10915977  1.          0.72888786]
 [-0.86757953  0.4865596  -1.          1.        ]
 [ 0.17360902  1.          0.64924381 -0.7191202 ]
 [ 0.70724542  0.44443406 -1.          0.1723325 ]
 [-1.          0.32934053  0.18558668 -0.50151063]
 [ 0.64487127 -0.16750277  0.63556306 -0.3197207 ]
 [-1.         -0.55921405  0.83075223  0.1982006 ]
 [-0.1632383   0.852107   -0.60037598 -0.88530243]
 [-0.89930207  0.99197313  1.         -0.1939439 ]
 [-1.         -0.01465816 -0.39790655  1.        ]
 [-1.         -0.051468

When finished, you can close the environment.

In [9]:
env.close()

### 4. It's Your Turn!

Now it's your turn to train your own agent to solve the environment!  When training the environment, set `train_mode=True`, so that the line for resetting the environment looks like the following:
```python
env_info = env.reset(train_mode=True)[brain_name]
```

In [76]:
import torch
import torch.nn as nn
import torch.nn.functional as F

conv = nn.Conv1d(1, 4, kernel_size=3,stride=1)
m = torch.randn(20, 1, 33)
print(m.shape)
output = conv(m)
print(output.shape)

torch.Size([20, 1, 33])
torch.Size([20, 4, 31])


In [83]:
import torch
import torch.nn as nn
import torch.nn.functional as F


# set up a convolutional neural net
# the output is the probability of moving right
# P(left) = 1-P(right)
class Policy(nn.Module):

    def __init__(self):
        super(Policy, self).__init__()

        ########
        ##
        ## Modify your neural network
        ##
        ########

        # 80x80x2 to 38x38x4
        # 2 channel from the stacked frame
        self.conv1 = nn.Conv1d(1, 4, kernel_size=6, stride=2, bias=False)
        # 38x38x4 to 9x9x16
        #self.conv2 = nn.Conv2d(4, 16, kernel_size=6, stride=4)
        self.size = (33 - 6)/2 + 1

        # two fully connected layer
        self.fc1 = nn.Linear(self.size, 256)
        self.fc2 = nn.Linear(256, 1)

        # Sigmoid to
        self.sig = nn.Sigmoid()

    def forward(self, x):
        ########
        ##
        ## Modify your neural network
        ##
        ########
        x = F.relu(self.conv1(x))
        #x = F.relu(self.conv2(x))
        # flatten the tensor
        x = x.view(-1, self.size)
        x = F.relu(self.fc1(x))
        return self.sig(self.fc2(x))

In [84]:
def collect_trajectories_unity(env, policy, n=20, tmax=200, nrand=5):
    """

    :param env:
    :param policy:
    :param n:
    :param tmax:
    :param nrand:
    :return:
    """
    device = 'cpu'
    brain_name = env.brain_names[0]
    brain = env.brains[brain_name]
    action_size = brain.vector_action_space_size
    env_info = env.reset(train_mode=True)[brain_name]

    for _ in range(tmax):
        actions = np.random.randn(n, action_size)  # select an action (for each agent)
        actions = np.clip(actions, -1, 1)  # all actions between -1 and 1
        env_info = env.step(actions)[brain_name]  # send all actions to tne environment
        next_states = env_info.vector_observations  # get next state (for each agent)
        rewards = env_info.rewards  # get reward (for each agent)
        dones = env_info.local_done  # see if episode finished


        # probs will only be used as the pi_old
        # no gradient propagation is needed
        # so we move it to the cpu
        next_states = np.reshape(next_states, (n,1,33))
        batch_input = torch.from_numpy(next_states).float().to(device)
        probs = policy(batch_input).squeeze().cpu().detach().numpy()


    # return pi_theta, states, actions, rewards, probability
    return probs, next_states, actions, rewards

In [85]:
policy = Policy()
collect_trajectories_unity(env, policy)

(array([0.4971966 , 0.50860286, 0.5140114 , 0.495563  , 0.49926996,
        0.5399385 , 0.6277315 , 0.5940321 , 0.5290594 , 0.5026178 ,
        0.5230253 , 0.56190026, 0.49045482, 0.46830243, 0.5096911 ,
        0.5544569 , 0.502032  , 0.53604686, 0.6069372 , 0.59568113,
        0.5435268 , 0.5784012 , 0.5795707 , 0.49090603, 0.5391347 ,
        0.4769761 , 0.47038496, 0.5226173 , 0.50343823, 0.56376624,
        0.6212648 , 0.5685368 , 0.51940465, 0.4940704 , 0.47624013,
        0.49733624, 0.49602008, 0.5085299 , 0.589407  , 0.57143575,
        0.535912  , 0.51613057, 0.6267579 , 0.54246485, 0.48997757,
        0.49248642, 0.45789745, 0.53131306, 0.52515143, 0.53275824,
        0.54316026, 0.5376099 , 0.51464987, 0.49758142, 0.62525105,
        0.5782937 , 0.4974975 , 0.453847  , 0.4661701 , 0.5075246 ,
        0.5033134 , 0.42420378, 0.4535659 , 0.5024908 , 0.5238227 ,
        0.4840917 , 0.5186768 , 0.5061878 , 0.50928736, 0.51650715,
        0.5483501 , 0.5465663 , 0.51955575, 0.52